language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

before_script:
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal-dev
  - sudo apt-get install libproj-dev
  - ./pkg-build.sh install_devtools
  - ./pkg-build.sh install_deps
  #- wget http://cran.r-project.org/src/contrib/Archive/rgdal/rgdal_1.2-5.tar.gz
  #- ./pkg-build.sh install_r_local rgdal_1.2-5.tar.gz
  #- rm rgdal_1.2-5.tar.gz
  - ./pkg-build.sh install_r rgdal

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_build
  - ./pkg-build.sh run_check

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
